# Testing Backpropogation code

In [1]:
from NeuralNets import FeedForwardNeuralNets
import numpy as np

X = np.array(
    [[1, 0, 1]]
)

Y = np.array(
    [[0, 0, 1]]
)


model = FeedForwardNeuralNets(X, [3], Y, optimizer="adam")


model.train(500)

In [3]:
model.evaluate(X[0])

array([8.32313488e-04, 6.99473478e-04, 9.98468213e-01])

In [4]:
Y_pred = []
for i in range(len(X)):
    Y_pred.append(model.evaluate(X[i]))

In [5]:
np.array(Y_pred), Y

(array([[8.32313488e-04, 6.99473478e-04, 9.98468213e-01]]), array([[0, 0, 1]]))

In [6]:
Y.shape[1]

3

In [7]:
model.parameters

{'W1': array([[ 0.1559491 , -0.59534598,  0.02337649],
        [ 1.11253317,  0.52711763,  1.21102024],
        [-0.51604917,  0.98596814, -0.50683382]]),
 'b1': array([0.88687105, 0.33197113, 1.40211302]),
 'W2': array([[-0.4115832 , -1.48675831, -0.58782822],
        [-0.21902098, -1.42000498, -0.4692655 ],
        [ 1.34422751,  1.80003479,  1.15448668]]),
 'b2': array([-0.22193922, -0.67182255,  1.45632139])}

In [8]:
import numpy as np 
from NeuralNets import FeedForwardNeuralNets
X = np.array([
    [0.1, 0.5, 0.2, 0.9, 0.3, 0.6, 0.4, 0.8, 0.7, 0.2],
    [0.3, 0.2, 0.7, 0.4, 0.6, 0.8, 0.9, 0.5, 0.1, 0.3],
    [0.8, 0.9, 0.4, 0.1, 0.5, 0.2, 0.7, 0.6, 0.3, 0.9],
    [0.6, 0.2, 0.3, 0.7, 0.4, 0.1, 0.8, 0.9, 0.5, 0.6],
    [0.5, 0.1, 0.8, 0.2, 0.9, 0.7, 0.3, 0.4, 0.6, 0.5],
    [0.7, 0.3, 0.6, 0.5, 0.8, 0.4, 0.1, 0.2, 0.9, 0.7],
    [0.2, 0.8, 0.1, 0.6, 0.4, 0.5, 0.7, 0.3, 0.2, 0.8],
    [0.9, 0.6, 0.5, 0.3, 0.7, 0.2, 0.4, 0.1, 0.8, 0.6],
    [0.4, 0.7, 0.9, 0.8, 0.2, 0.3, 0.6, 0.5, 0.1, 0.4],
    [0.5, 0.3, 0.7, 0.4, 0.1, 0.8, 0.2, 0.6, 0.7, 0.5]
])

y = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])
num_classes = len(np.unique(y))
y_one_hot = np.eye(num_classes)[y]

print("One-hot encoded y:")
print(y_one_hot)

One-hot encoded y:
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [9]:
y.shape

(10,)

In [10]:
y_one_hot.shape

(10, 2)

In [11]:
from lossfunctions import LossFunctions
from activations import Activations

squaredError = LossFunctions.SquaredErrorLoss()
linear = Activations.Linear()

model = FeedForwardNeuralNets(X, [10], y, optimizer="adam", O=linear, L=squaredError)


model.train(5000)

In [15]:
model.parameters

{'W1': array([[-1.58535301,  1.0642294 , -0.59078827,  0.2532779 , -0.21750416,
          1.01450647, -0.30460906, -1.09101799, -1.93226555, -1.13683003],
        [ 1.92490259, -1.36967649, -0.33714316, -0.85383308, -0.21537691,
         -0.72404152,  1.37262329, -0.57170264, -0.06467089,  0.40730963],
        [-0.69686003, -0.41470769,  3.14593088, -4.10801332,  0.99110561,
         -0.51931332, -1.54213237, -0.83356154, -2.79396896,  1.24524718],
        [ 0.93735284, -1.69739257,  0.55915956,  0.45928351, -2.38372465,
          1.89509825,  2.18950148, -1.1731903 , -2.02593343, -1.08494988],
        [-1.24135666,  1.6374435 ,  1.40515731, -2.05553883,  0.99020343,
         -1.74954629,  0.94400171,  1.39346432, -0.7377718 , -0.04014289],
        [-0.08997475,  1.26542782,  0.92453895,  1.86803537,  0.7388022 ,
         -2.65493553, -0.21108293, -1.86022558, -2.20201528, -1.87390291],
        [-2.45197122,  0.35304002, -0.16171061,  1.89849987, -0.4981151 ,
         -0.79566622, -0.7

In [12]:
for i in X:
    print(model.evaluate(i))

[0.99978928]
[1.89235588e-05]
[1.00037457]
[-3.28599033e-05]
[0.99932139]
[0.0005834]
[0.99965203]
[-0.00154621]
[1.00009625]
[-0.00072154]
