# Testing Backpropogation code

In [3]:
from NeuralNets import FeedForwardNeuralNets
import numpy as np

X = np.array(
    [[1, 0, 1]]
)

Y = np.array(
    [[0, 0, 1]]
)


model = FeedForwardNeuralNets(X, [3], Y, optimizer="adam")


model.train(500)

In [4]:
model.evaluate(X[0])

array([0.00102595, 0.0021099 , 0.99686416])

In [7]:
Y_pred = []
for i in range(len(X)):
    Y_pred.append(model.evaluate(X[i]))

In [8]:
np.array(Y_pred), Y

(array([[0.00685056, 0.00837635, 0.98477309]]), array([[0, 0, 1]]))

In [6]:
Y.shape[1]

3

In [2]:
model.parameters

{'W1': array([[ 0.25997786, -0.17809446,  0.20110253],
        [-0.32590173, -1.03563709,  0.2516722 ],
        [-0.69068281,  0.85859981, -0.55948823]]),
 'b1': array([ 0.07146537,  1.64966975, -0.81977554]),
 'W2': array([[0.67419371, 0.15185992, 0.44700593],
        [0.9744497 , 0.9956726 , 0.45230695],
        [0.89104049, 0.93548917, 0.43082721]]),
 'b2': array([0.90336002, 0.9612695 , 0.7919596 ])}

In [6]:
import numpy as np 
from NeuralNets import FeedForwardNeuralNets
X = np.array([
    [0.1, 0.5, 0.2, 0.9, 0.3, 0.6, 0.4, 0.8, 0.7, 0.2],
    [0.3, 0.2, 0.7, 0.4, 0.6, 0.8, 0.9, 0.5, 0.1, 0.3],
    [0.8, 0.9, 0.4, 0.1, 0.5, 0.2, 0.7, 0.6, 0.3, 0.9],
    [0.6, 0.2, 0.3, 0.7, 0.4, 0.1, 0.8, 0.9, 0.5, 0.6],
    [0.5, 0.1, 0.8, 0.2, 0.9, 0.7, 0.3, 0.4, 0.6, 0.5],
    [0.7, 0.3, 0.6, 0.5, 0.8, 0.4, 0.1, 0.2, 0.9, 0.7],
    [0.2, 0.8, 0.1, 0.6, 0.4, 0.5, 0.7, 0.3, 0.2, 0.8],
    [0.9, 0.6, 0.5, 0.3, 0.7, 0.2, 0.4, 0.1, 0.8, 0.6],
    [0.4, 0.7, 0.9, 0.8, 0.2, 0.3, 0.6, 0.5, 0.1, 0.4],
    [0.5, 0.3, 0.7, 0.4, 0.1, 0.8, 0.2, 0.6, 0.7, 0.5]
])

y = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])
num_classes = len(np.unique(y))
y_one_hot = np.eye(num_classes)[y]

print("One-hot encoded y:")
print(y_one_hot)

One-hot encoded y:
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [12]:
from lossfunctions import LossFunctions
from activations import Linear

squaredError = LossFunctions.SquaredError()


model = FeedForwardNeuralNets(X, [10], y_one_hot, optimizer="adam")


model.train(5000)

In [13]:
for i in X:
    print(model.evaluate(i))

[0.00167127 0.99832873]
[0.9953784 0.0046216]
[4.38098471e-04 9.99561902e-01]
[9.99685362e-01 3.14638319e-04]
[0.00789626 0.99210374]
[0.99327361 0.00672639]
[3.65150055e-04 9.99634850e-01]
[9.99461116e-01 5.38884305e-04]
[0.00161463 0.99838537]
[0.9959225 0.0040775]
